vocab_source: 5001
vocab_target: 5001
optimizer: adamw
scheduler: cosine
dropout: 0.4
hidden_size: 512 
embedding_size: 128
learning_rate: 1e-3
batch_size: 64
epochs: 100
num_layers: 4
dot_product: true