num_epochs: 20
vocab_source: 5001
vocab_target: 5001
optimizer: adamw # heuristic choice
scheduler: cosine # heuristic choice
dropout: 0.4 # heuristic choice
hidden_size: 512 # heuristic choice
embedding_size: 128 # heuristic choice
learning_rate: 0.001 # personal choice
batch_size: 64 # personal choice
num_layers: 4 # personal choice
dot_product: false # heuristic choice